{{- if and .Values.postgresql.enabled .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  namespace: {{ include "agentic-claims-demo.namespace" . }}
  labels:
    {{- include "agentic-claims-demo.labels" . | nindent 4 }}
    app: postgresql
type: Opaque
stringData:
  POSTGRES_ADMIN_PASSWORD: {{ quote .Values.secrets.postgresAdminPassword }}
  {{ quote .Values.postgresql.auth.secretKeys.databaseKey }}: {{ quote .Values.postgresql.auth.database }}
  {{ quote .Values.postgresql.auth.secretKeys.userNameKey }}: {{ quote .Values.postgresql.auth.username }}
  {{ quote .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ quote .Values.secrets.postgresPassword }}
{{- end }}
