---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "agentic-claims-demo.namespace" . }}
  labels:
    {{- include "agentic-claims-demo.labels" . | nindent 4 }}
    opendatahub.io/dashboard: "true"
{{- if .Values.inference.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "inference.namespace" . }}
  labels:
    {{- include "agentic-claims-demo.labels" . | nindent 4 }}
    opendatahub.io/dashboard: "true"
{{- end }}
{{- if .Values.embedding.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "embedding.namespace" . }}
  labels:
    {{- include "agentic-claims-demo.labels" . | nindent 4 }}
    opendatahub.io/dashboard: "true"
{{- end }}
